apiVersion: v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: edu-nodeapp
    spec:
      containers:
      - name: nodeapp-container
        image: mycluster.icp:8500/edu/nodeapp:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1