apiVersion: v1
kind: Service
metadata:
  labels:
    app: edu-reactapp
  name: reactapp-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: edu-reactapp
  type: LoadBalancer